name: Build StockFullAPK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Full Kivy APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          recipe: python3,kivy
          arch: arm64-v8a
          title: StockFullAI
          package: com.stock.fullai
          version: 1.0

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: StockFullAI-APK
          path: bin/*.apk
